minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - "@shbernal/*"

allowBuilds:
  esbuild: true
  lefthook: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
