minimumReleaseAgeStrict: true
minimumReleaseAgeExclude:
  - "@shbernal/*"
  - flashcard-md-spec@1.0.0

allowBuilds:
  esbuild: true
  lefthook: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
